Traceback (most recent call last):
  File "get_vibrations.py", line 847, in <module>
    main()
  File "get_vibrations.py", line 484, in main
    data=open(folder+'/'+filename)
IOError: [Errno 2] No such file or directory: 'MoS2.i_atom_0.i_coord_0.displ_-0.002/aims.out'
